language: c
matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      services:
        - docker
      env:
        - label=format-check
      before_install: *bi
      script:
        - make -f misc/docker-ci/check.mk format-check CONTAINER_NAME=kazuho/h2o-ci:ubuntu1904
